import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className}>
            <nav className="navbar">
                <div><Link href="/" className="point">Home</Link></div>
                <div><Link href="/list">List Page</Link></div>
                <div><Link href="/memo">Memo Page</Link></div>
                <div><Link href="/swiper-test">Swiper Page</Link></div>
            </nav>
            {children}
        </body>
    </html>
  );
}
